### ISSUE TITLE
will need a update to work with new NVDA speech API

### ISSUE THREAD

**Issue by tapper82** [pumper42nickel/eloquence_threshold#34]
Hi the NVDA speach API has bin updated after nvda_snapshot_alpha-28161,b93fc546 
Here's a link to the API change. https://github.com/nvaccess/nvda/commit/e77bde9a5f50df276eab9008e280850d3a727bc7
Here's a link to where I thought that it was a simple change in NVDA.
https://github.com/nvaccess/nvda/issues/14909
I hope we can get a update to fix this pleas. Thanks for keeping this going for so long.

**Comment by dreinn** [comment]
Yes, I can confirm that synthring settings is not working anymore, and that the driver is not able to collect all information passed by NVDA. For example, go to desktop, you will see that the first item is not announced anymore. Or try to navigate on the advanced preference window of NVDA, when you change from group to group, the first item is not announced.

**Comment by tapper82** [comment]
Bump!

**Comment by tapper82** [comment]
Bump! Any news On a update to work with latest NVDA builds?

**Comment by Elshara** [comment]
I doubt it. We're on borrowed time until another stable comes out and it won't work at all.

**Comment by serrebi** [comment]
Thanks for all the years of DRM free eloquence. I've purchased it, so I use the good version! Hope a fix will be incoming.

**Comment by lbk2907** [comment]
Excuse me, are you use the code factory version? Just want to know. Thanks.

**Comment by tapper82** [comment]
@lbk2907 No mate the one off this site.

**Comment by lbk2907** [comment]
@tapper82 Sorry. I not really understand what you mean. Not verry well in english haha.

**Comment by Elshara** [comment]
I know when the next stable release of NVDA comes out eloquence will break. I'm on borrowed time.

**Comment by Elshara** [comment]
If you guys want working eloquence versions in the mean time that's portable, you can visit this group for updates.
https://t.me/WindowsScreenReaderDotCom

**Comment by tapper82** [comment]
I don't have TELEGRAM.

**Comment by pumper42nickel** [comment]
So what exactly is not working? I just tested with stable v2023.1 and latest   alpha-28419 - the version built from source code appears to work fine. Note that we don't provide compatibility with alphas, only with stable versions. You guys need to learn to provide bug description and steps to reproduce if you wnat your issue to be fixed. Also please don't spread panic here, eloquence_threshold is very alive and will be maintained in the near future.

**Comment by Elshara** [comment]
I will be clear.
For the past, several, releases of alpha updates to NVDA, Eloquence specifically bugs out when attempting to retrieve contextual item information.
Example:
Reading how ever many list items there are on the desktop. Saying selected when highlighting text or files.
The behaviour of Eloquence goes silent prematurely and it will not retrieve all of the contextual information NVDA feeds to it using the speech API.
All we are asking, is that this behaviour be repaired. We should not be forced to rely on stable NVDA versions, particularly if Alpha releases fixes buggy or unresponsive sluggish performance such as in Windows 11. NVDA is the only screen reader trying to smooth out the challenges Windows as a whole creates.
You may not, find it necessary to keep up with alpha releases of NVDA. And in the past, it was not required to do so at all for minor addons such as  speech synthesizers. In the past years worth o development however, NVDA developers have taken a stronger stance on third party synthesizer addons. Limiting how they function, in an attempt to discourage the use of Eloquence specifically. An issue you may not be aware of, it is not just your synthesizer fork of Eloquence effected. IBM TTS also is, however due to the fact that its driver is packaged separately from Eloquence files, they have been able to keep more up to date with fixing this kind of minor bug NVDA intentionally adds to its source code.
People who use your fork of eloquence as their daily driver, appreciate the functionality of a faster, snappier system. With the degree of professionalism and customization Eloquence has always provided. And as always, people do not realize back end solutions like API information retrieval for example, can be engineered to fail on purpose forcing people to deal with the inconvenience and incompetence of poorly performing work tools.
I am a strong believer in blind independence, so my work area is as stable as possible. I find it troubling that we are still facing these kind of problems, even after Apple made Eloquence freely available to all macs. I warmly appreciate the attention to detail you have provided making this synth alone the only reason why I am on Windows. I'd be using Linux otherwise, and I would be getting less out of it as Orca plus Voxin is not an ideal combination at best.
We are not coming here to complain about compatibility, as much as we are all here to appreciate updates when they happen to avoid compatibility issues with seemingly rushed to be outdated software. Speaking for myself, I only wish everyone to have a smooth transition between updates, and to have someone stand in the way of NVDA developers making our need for Eloquence a pain in the arse to administer.
Yes, this means that much to me, that over the years, I have donated hundreds of dollars to various projects, to maintain Eloquence development. On Android, on Linux, on Windows and even going as far as to pay money to virtual machine software to get it working on Mac. I am an avid eloquence fan and always have been. I likely always will be, and was during Apple's testing phase, the loudest critic against its butchering of how Eloquence sounded as they attempted to brand it like they did with Fred. I wasn't going to let that happen. Nor will I not speak up to the very people like you, whom I support standing in the way of NVDA interrupting proper speech flow of Eloquence because they dislike it and expect a leggy outdated speech platform to take its place. I expect nothing short of AI will ever be able to emulate this functionality as effectively as Eloquence can and has for literal decades.
You can tell I'm passionate about it. The days are quickly passing us by, where we can not afford to just use stable NVDA versions anymore. It is a solution, but not a fix. I for one, would really appreciate it if you would in future, try to pay closer attention to NVDA Alpha release schedules as this will give you a precursor insight into their stable release plans beyond just a simple Python version manifest upgrade. As I have noticed, the time it takes for stable releases to come out of NVDA, is longer...while app updates everywhere else is shorter. What makes this especially and particularly obvious, is that I suspect NVDA tends to monitor projects like this, for any development release schedule. Putting the power in NVDA's pocket to undermine our efforts to work stronger together as a community, even as contributors, means that although they brand themselves as for the people, they are clearly governed by corporate interests as they act as though they can be taken down by them if they aren't followed. In a way, this isn't what NVDA used to stand for at all, I don't wish to see our community derailed to the point of no return over it.
Thank you for hearing me.

**Comment by pumper42nickel** [comment]
Let me repeat again: provide step by step description of how to reproduce the problem. Provide NVDA version, windows version etc. 
Steps to repro:
1. Open program XXX
2. Pres button YYY

Expected behavior
* blablabla is spoken
Actual behavior:
* Something else is spoken

I only have a free weekend once in a blue moon and instead of spending my time fixing the issue I am wasting my time trying to figure out what is not working from your confusing comments. Try to be more respectful of developers time when reporting an issue.
> Reading how ever many list items there are on the desktop
How do I do that?
> Saying selected when highlighting text or files
In Windows explorer when I select an item with Control+Up/Down or Control+Space it works as expected in latest alpha.

**Comment by Elshara** [comment]
Finally, we are...communicating.
I think you may be a better candidate to take your own advice to heart. As I am attempting to promote a polite discussion around this issue - which you clearly understand - so that we have something to focus on while awaiting the next update. In order to deter other people from being impatient and add to your apparently busy life.
I do not regret what I have said. Eloquence is important to me. I will however, apologize for stressing you out as I did not mean to overwhelm or confuse you. Please take as much time as you need to for taking care of yourself.

**Comment by tapper82** [comment]
OK here gos;

In any build of NVDA newer than nvda_snapshot_alpha-28161,b93fc546 
All builds of windows.
First letter navigation  on the desktop and in any folder view will not work. 
Tool tips are not spoken.
When a webpage is opened in any browser speech will not start until the arrow keys are used, even when NVDA is set to start talking on page load.

**Comment by pumper42nickel** [comment]
@tapper82, ok, I managed to reproduce your use case with first letter navigation. Still couldn't repro with tooltips, but assuming the same root cause. Will dig more into this.

**Comment by pumper42nickel** [comment]
Ok, I figured root cause, it appears that WasapiWavePlayer.feed() doesn't respect onDone argument, and as a result index callbacks are not working. Likely this will be fixed in NVDA before it goes stable and nmot much can be done on my end. And this is the reason why we don't provide compatibility with alpha versions. So relax everybody, when next version goes stable we'll fix eloquence.

**Comment by tapper82** [comment]
Hi @pumper42nickel Mate it's not going to be fixt in NVDA. This is how the new API for speach  will work. Pleas see my links in first post.

**Comment by pumper42nickel** [comment]
Ok, I think I fixed it in v0.20230702.01.
Note that in the future I will not address bugs with alpha versions of NVDA. Feel free to report bugs though.
Also bugs without clear repro steps will not be addressed.

**Comment by Elshara** [comment]
Thank you for the update! It is very much appreciated.
The good news is, you released this on my birthday.
The bad news is, I don't want to ruin my birthday to find out if it's true. So I will voluntarily be in suspense until tomorrow. lol

**Comment by tapper82** [comment]
Hi just updated to latest build of NVDA And latest eloquence. All looks to be working just as it should thanks. I will post back if I find any more bugs. Thanks for your work on this. I know you don't like to do fixes to alpha builds, but this would not of changed for a release build mate. More of NVDA devs had said so in the links I posted.

**Comment by alexstine** [comment]
@pumper42nickel I actually reported this here: https://github.com/nvaccess/nvda/issues/15710. I did not think to check this GitHub for a fix. Thanks for the hard work keeping this add-on updated. I agree with others, it's a real shame NVDA developers keep breaking 3rd-party add-ons support. I'll open a new issue here if I can spot further bugs.

**Comment by alexstine** [comment]
Confirmed working in latest stable. Thanks again. 👍

**Comment by tapper82** [comment]
Still working grate. I will close now.

**Comment by tapper82** [comment]
Hi this is broken again in latest NVDA beta 1

**Comment by tapper82** [comment]
Traceback (most recent call last):
  File "extensionPoints\__init__.pyc", line 117, in apply
  File "extensionPoints\util.pyc", line 230, in callWithSupportedKwargs
  File "speech\languageHandling.pyc", line 39, in getSpeechSequenceWithLangs
  File "synthDriverHandler.pyc", line 332, in languageIsSupported
  File "languageHandler.pyc", line 450, in normalizeLanguage
AttributeError: 'NoneType' object has no attribute 'replace'
ERROR - extensionPoints.Filter.apply (10:13:17.276) - MainThread (8096):
Error running handler <function getSpeechSequenceWithLangs at 0x045BE4D8> for <extensionPoints.Filter object at 0x045B8710>
Traceback (most recent call last):
  File "extensionPoints\__init__.pyc", line 117, in apply
  File "extensionPoints\util.pyc", line 230, in callWithSupportedKwargs
  File "speech\languageHandling.pyc", line 39, in getSpeechSequenceWithLangs
  File "synthDriverHandler.pyc", line 332, in languageIsSupported
  File "languageHandler.pyc", line 450, in normalizeLanguage
AttributeError: 'NoneType' object has no attribute 'replace'
ERROR - extensionPoints.Filter.apply (10:13:17.281) - MainThread (8096):
Error running handler <function getSpeechSequenceWithLangs at 0x045BE4D8> for <extensionPoints.Filter object at 0x045B8710>
Traceback (most recent call last):
  File "extensionPoints\__init__.pyc", line 117, in apply
  File "extensionPoints\util.pyc", line 230, in callWithSupportedKwargs
  File "speech\languageHandling.pyc", line 39, in getSpeechSequenceWithLangs
  File "synthDriverHandler.pyc", line 332, in languageIsSupported
  File "languageHandler.pyc", line 450, in normalizeLanguage
AttributeError: 'NoneType' object has no attribute 'replace'
ERROR - extensionPoints.Filter.apply (10:13:17.946) - MainThread (8096):
Error running handler <function getSpeechSequenceWithLangs at 0x045BE4D8> for <extensionPoints.Filter object at 0x045B8710>
Traceback (most recent call last):
  File "extensionPoints\__init__.pyc", line 117, in apply
  File "extensionPoints\util.pyc", line 230, in callWithSupportedKwargs
  File "speech\languageHandling.pyc", line 39, in getSpeechSequenceWithLangs
  File "synthDriverHandler.pyc", line 332, in languageIsSupported
  File "languageHandler.pyc", line 450, in normalizeLanguage
AttributeError: 'NoneType' object has no attribute 'replace'
ERROR - extensionPoints.Filter.apply (10:13:18.376) - MainThread (8096):
Error running handler <function getSpeechSequenceWithLangs at 0x045BE4D8> for <extensionPoints.Filter object at 0x045B8710>
Traceback (most recent call last):
  File "extensionPoints\__init__.pyc", line 117, in apply
  File "extensionPoints\util.pyc", line 230, in callWithSupportedKwargs
  File "speech\languageHandling.pyc", line 39, in getSpeechSequenceWithLangs
  File "synthDriverHandler.pyc", line 332, in languageIsSupported
  File "languageHandler.pyc", line 450, in normalizeLanguage
AttributeError: 'NoneType' object has no attribute 'replace'
ERROR - extensionPoints.Filter.apply (10:13:20.890) - MainThread (8096):
Error running handler <function getSpeechSequenceWithLangs at 0x045BE4D8> for <extensionPoints.Filter object at 0x045B8710>
Traceback (most recent call last):
  File "extensionPoints\__init__.pyc", line 117, in apply
  File "extensionPoints\util.pyc", line 230, in callWithSupportedKwargs
  File "speech\languageHandling.pyc", line 39, in getSpeechSequenceWithLangs
  File "synthDriverHandler.pyc", line 332, in languageIsSupported
  File "languageHandler.pyc", line 450, in normalizeLanguage
AttributeError: 'NoneType' object has no attribute 'replace'
ERROR - extensionPoints.Filter.apply (10:13:21.383) - MainThread (8096):
Error running handler <function getSpeechSequenceWithLangs at 0x045BE4D8> for <extensionPoints.Filter object at 0x045B8710>
Traceback (most recent call last):
  File "extensionPoints\__init__.pyc", line 117, in apply
  File "extensionPoints\util.pyc", line 230, in callWithSupportedKwargs
  File "speech\languageHandling.pyc", line 39, in getSpeechSequenceWithLangs
  File "synthDriverHandler.pyc", line 332, in languageIsSupported
  File "languageHandler.pyc", line 450, in normalizeLanguage
AttributeError: 'NoneType' object has no attribute 'replace'
ERROR - extensionPoints.Filter.apply (10:13:21.939) - MainThread (8096):
Error running handler <function getSpeechSequenceWithLangs at 0x045BE4D8> for <extensionPoints.Filter object at 0x045B8710>
Traceback (most recent call last):
  File "extensionPoints\__init__.pyc", line 117, in apply
  File "extensionPoints\util.pyc", line 230, in callWithSupportedKwargs
  File "speech\languageHandling.pyc", line 39, in getSpeechSequenceWithLangs
  File "synthDriverHandler.pyc", line 332, in languageIsSupported
  File "languageHandler.pyc", line 450, in normalizeLanguage
AttributeError: 'NoneType' object has no attribute 'replace'
ERROR - extensionPoints.Filter.apply (10:13:22.396) - MainThread (8096):
Error running handler <function getSpeechSequenceWithLangs at 0x045BE4D8> for <extensionPoints.Filter object at 0x045B8710>
Traceback (most recent call last):
  File "extensionPoints\__init__.pyc", line 117, in apply
  File "extensionPoints\util.pyc", line 230, in callWithSupportedKwargs
  File "speech\languageHandling.pyc", line 39, in getSpeechSequenceWithLangs
  File "synthDriverHandler.pyc", line 332, in languageIsSupported
  File "languageHandler.pyc", line 450, in normalizeLanguage
AttributeError: 'NoneType' object has no attribute 'replace'

**Comment by tapper82** [comment]
Fixt in NVDA 2025.3
