### ISSUE TITLE
Eloquence crash, error processing unicode character

### ISSUE THREAD

**Issue by dreinn** [pumper42nickel/eloquence_threshold#8]
Hello,
There is a problem with some characters, suddenly the addon crash!!! I paste the relevant part of the log, I hope you can fix it.
And obviously, thank you very much for your efforts.

ERROR - stderr (12:33:54.695) - Thread-1 (11436): 
Exception in thread Thread-1: 
Traceback (most recent call last): 
   File "threading.pyc", line 926, in _bootstrap_inner 
   File "C:\Users\fufu\AppData\Roaming\nvda\addons\Eloquence\synthDrivers\_eloquence.py", line 88, in run 
     internal_process_queue() 
   File "C:\Users\fufu\AppData\Roaming\nvda\addons\Eloquence\synthDrivers\_eloquence.py", line 314, in internal_process_queue 
     func(*args) 
   File "C:\Users\fufu\AppData\Roaming\nvda\addons\Eloquence\synthDrivers\_eloquence.py", line 262, in speak 
     text = text.encode("ansi") 
UnicodeEncodeError: 'mbcs' codec can't encode characters in position 0--1: invalid character

**Comment by dreinn** [comment]
ok, I see I have an old version of the addon.
It is dated august 16!
Is there the new addon packaged for NVDA?
I'd like to test the new code!
Thank you

**Comment by dreinn** [comment]
I replaced the eloquence.py and _eloquence.py file, now the situation is ok!!! Thank you very much!
